project:
  type: website

website:
  title: "dashboard.tesselle"
  description: |
    tesselle is a collection of [R](https://www.r-project.org/) packages for
    research and teaching in archaeology. These packages focus on quantitative
    analysis methods developed for archaeology. The tesselle packages are
    designed to work seamlessly together and to complement general-purpose and
    other specialized statistical packages.

  site-url: https://dashboard.tesselle.org
  repo-url: https://github.com/tesselle/dashboard
  repo-actions: [edit, issue]

  favicon: /images/icons/favicon.ico
  image: /images/card.png
